# Generated by Django 5.0 on 2023-12-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پشتیبان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع همکاری')),
            ],
        ),
    ]
