# Generated by Django 5.0 on 2023-12-27 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.PositiveIntegerField(verbose_name='زمان آماده سازی')),
                ('delay', models.PositiveIntegerField(default=0, verbose_name='میزان تاخیر این سفارش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر سفارش')),
                ('sent', models.BooleanField(default=False, verbose_name='وضعیت ارسال سفارش')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendors.vendor', verbose_name='فروشگاه')),
            ],
        ),
        migrations.CreateModel(
            name='DelayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW_DELIVERY_TIME', 'زمان آماده سازی جدید ارائه شده'), ('WAIT_FOR_AGENT', 'منتظر انتخاب پشتیبان'), ('IN_PROGRESS', 'در حال بررسی'), ('FINISHED', 'به پایان رسیده')], default='WAIT_FOR_AGENT', max_length=50, verbose_name='وضعیت گزارش')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت گزارش')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agents.agent', verbose_name='پشتیبان بررسی کننده این گزارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order', verbose_name='سفارش مربوط به این گزارش')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERED', 'سفارش به مقصد رسیده'), ('PICKED', 'دریافت سفارش'), ('AT_VENDOR', 'در فروشگاه'), ('ASSIGNED', 'پیک در راه فروشگاه')], default='ASSIGNED', max_length=50, verbose_name='وضعیت سفر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفر')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='google_credentials', to='orders.order')),
            ],
        ),
    ]
